### ISSUE TITLE
Checar token por rota

### ISSUE THREAD

**Issue by giolvani** [leoniralves/Slim-OAuth2-Eloquent#3]
Existe algum jeito de eu verificar a existência do token pela rota ou grupo. Não quero fazer a verificação para todas as rotas.

Obrigado

**Comment by giolvani** [comment]
Tente criar o seguinte método estático em \API\Middleware\AuthenticationTokenOAuth.php:

``` php
public static function routeMiddleware($server)
{
    $oauth = new AuthenticationTokenOAuth($server);

    return function() use ($oauth)
    {
        $oauth->call();
    };
}
```

Ele até faz a chamada para o método call, cai na exceção, mas não está parando a execução como deveria.

**Comment by leoniralves** [comment]
Olá @giolvani! Desculpa a demora para lhe responder, mas a correria não da folga :)
Cara... Vou dar uma olhada nessa questão que vc levantou, mas se vc já tiver resolvido, manda um pull request que será bem vindo!

**Comment by giolvani** [comment]
Olá Leonir, na verdade eu criei um middleware separado pra fazer isso, não cheguei a mexer na lib. Mas posso tentar algo e dar um pull.
