### ISSUE TITLE
O payload para Refresh é o mesmo que para solicitar um token ?

### ISSUE THREAD

**Issue by aluferraz** [leoniralves/Slim-OAuth2-Eloquent#4]
Olá,

Parabens pela iniciativa ! Um dúvida :

No seu exemplo não vi diferença entre o payload de criar um token e o de solicitar refresh de um token. Não deveria ter o parametro "refresh_token" no payload de atualização ?

**Comment by aluferraz** [comment]
Na verdade debuguei aqui e é apenas um erro na documentação do seu github.
O grant_type deve ser "refresh_token" e o password omitido..

**Comment by leoniralves** [comment]
Olá @aluferraz,
Obrigado pelo feedback. Se quiser contribuir com o projeto, será muito bem vindo.
